name: Production Schedule Facade CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/ProductionSchedule

    - name: Build project
      run: dotnet build ProductionScheduleFacade.sln --configuration Release
      working-directory: ./src/ProductionSchedule
      
    - name: Publish artifacts
      run: dotnet publish --configuration Release --output ./publish
      working-directory: ./src/ProductionSchedule

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: csharp-artifacts
        path: ./publish
